### ISSUE TITLE
Cearadactylus, Deinosuchus, Mammoth, and Leptictidium sounds

### ISSUE THREAD

**Issue by PCAwesomeness** [JurassiCraft/JurassiCraft#133]
I see there's sounds for Cearadactylus, Leptictidium, and the wooly mammoth. Can someone add them to the sounds.json file?

Also, here's some sounds that you should also put in the sounds.json file:

http://www.mediafire.com/download/vb29hgtmwht85ad/Deinosuchus+Sounds.zip

**Comment by Kash-117** [comment]
Don't worry we have around 600 or more sound files that we need to go through and find the sounds for them.
