### ISSUE TITLE
Animated mobs scratch themselves with their tail

### ISSUE THREAD

**Issue by PCAwesomeness** [JurassiCraft/JurassiCraft#134]
Sometimes, the animated mobs's tails will derp out and look like they're being used to scratch their hips. Can this be fixed?

**Comment by BobMowzie** [comment]
Could you describe the issue a bit more literally and less creatively?

**Comment by PCAwesomeness** [comment]
OK.

Sometimes, this happens:

http://imgur.com/7wkPqC9

And for some reason, it stops whenever you enter Theater Mode (F1)...

**Comment by BobMowzie** [comment]
Woah. I haven't seen this. It just happens randomly? How long does it stay like that?
Raf is going to have to take a look at this.

**Comment by PCAwesomeness** [comment]
It happens randomly, and stays like that for 5-9 seconds.

**Comment by BobMowzie** [comment]
How frequently does this happen?

**Comment by PCAwesomeness** [comment]
Every 15 seconds.

**Comment by BobMowzie** [comment]
I can't reproduce it. We'll see what we can do.

**Comment by PCAwesomeness** [comment]
Yeah. It only goes away if you're away from them or if you're in Theater Mode (F1).

**Comment by Kash-117** [comment]
Yeah this is a tail buffering bug, the tail buffering thing is new,

**Comment by PCAwesomeness** [comment]
This isn't fixed, please reopen this.

**Comment by BobMowzie** [comment]
It is fixed!

**Comment by PCAwesomeness** [comment]
This coelacanth says otherwise...

http://imgur.com/xTTcC0B

Also, I'm on the latest build.

**Comment by BobMowzie** [comment]
We just fixed it today. We haven't released it yet.

**Comment by PCAwesomeness** [comment]
So build #88 is not the build I was looking forward to?

**Comment by BobMowzie** [comment]
WAIT we did release it.

WHAT.

Okay, is the coelacanth surrounded by any other coelacanths?
I still cannot replicate this.

**Comment by PCAwesomeness** [comment]
@BobMowzie 

It isn't.

**Comment by BobMowzie** [comment]
I'm sorry, but I haven't seen this at all. Could you try removing any other mods and see if it still happens? I highly doubt this is it, but who knows.
