### ISSUE TITLE
A comment to Issue #83

### ISSUE THREAD

**Issue by PCAwesomeness** [JurassiCraft/JurassiCraft#136]
Apparently, as issue #83 is locked and limited to collaborators, I have a comment.

Can you add Triceratops and Cearadactylus to the list and remove the coelacanth from the list (it has a new model)?

Also, Meganeura probably needs a new model.

**Comment by BobMowzie** [comment]
Don't worry, PCA. We have other ways of keeping track of these things. We don't need to update the Github issue.
