### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by gegy1000** [JurassiCraft/JurassiCraft#138]
Client crashes when you click the arrow in the creative inventory to go to next list of tabs. Only happens when you are on a dedicated server.

**Comment by iLexiconn** [comment]
Post the crash log please

**Comment by gegy1000** [comment]
Incompatibility with another mod..

**Comment by Maokuma** [comment]
Sorry if I'm rude, but as I and my friends love this mod, I tested this mod with a few possible "forge mod" combinations in game to see if I could help out. But I could not make it crash. 1.7.10 with forge and Nei at the core.
I usually put crash logs at http://pastebin.com/ and link it to Github, if you need a link.

**Comment by Kash-117** [comment]
Thanks for the testing, we'll have to keep trying to emulate the crash just in case though
