### ISSUE TITLE
Hostile mobs do not attack player unless provoked

### ISSUE THREAD

**Issue by BobMowzie** [JurassiCraft/JurassiCraft#142]

**Comment by PCAwesomeness** [comment]
For some reason, all hostile mobs are neutral except for Tyrannosaurus.

**Comment by PCAwesomeness** [comment]
This issue is fixed, and so, it should be closed.

**Comment by PCAwesomeness** [comment]
This issue came back again. Reopen this, please.

**Comment by Kash-117** [comment]
They become non hostile to creative mode players.
