### ISSUE TITLE
Failed Extended properties for EntityPregnantCowJC

### ISSUE THREAD

**Issue by Maokuma** [JurassiCraft/JurassiCraft#144]
I guess you already know about this, but I'll past it here just in case.
http://pastebin.com/rjCvsGV8 (It's at the bottom of the log.)

Using Jurassicraft build 91 when testing Chocolate quest and Fastcraft.

Thanks for your work!

**Comment by RafaMv0** [comment]
You are probably using an old world that created vanilla mobs with an old
build. One of the latest builds are not compatible with these vanilla mobs.
Pretty sure that you lost your world (it is corrupted). I would recommend a
backup before testing nem builds. Can you confirm if your world was created
using an old version of our mod? Thanks

>

**Comment by Maokuma** [comment]
The re-create world button is a curse.
I tested with removing chocolate craft 1.7.10 beta2 and did the re-created world thingie, it worked!
I also tested with just Dino and chocolate with re-create and to my surprise, it worked!
On the last one, It could be a combination of my IQ and the removal of Biomes o plenty that I used at first. But I did test the recreate button with just these two.

Starting a totally new save worked, making me think if this is a biome or an odd chocolate quest thingie that spawns close to the player. I don't know if it has an in-game impact due to that but I'll test more when I get time.

**Comment by TheLarsinator** [comment]
What is Chocolate quest? Is that a different mod?

**Comment by Maokuma** [comment]
I have not been able to find any in game issues in regard to the error.
Chocolate quest is an dungeon spawning mod that comes with customized mob spawner's that react to players that gets close. (monsters and boss like mobs.)
(http://chocolatequest.wikia.com/wiki/The_Chocolate_Quest_Wiki)

If the error poses no problem in itself, I would write it of the checklist. But I'm no expert.
