### ISSUE TITLE
Tylosaurus has seizures when put in a river

### ISSUE THREAD

**Issue by PCAwesomeness** [JurassiCraft/JurassiCraft#150]
Whenever I put Tylosaurus in a river, it spazzes out a lot.

**Comment by BobMowzie** [comment]
Does this happen with other swimming mobs?

**Comment by PCAwesomeness** [comment]
Tylosaurus is the only one that has the newest swimming AI. What do you think?

**Comment by BobMowzie** [comment]
Oh. LittleBreadLoaf will have to take a look.

**Comment by PCAwesomeness** [comment]
OK, this is fixed now.

**Comment by PCAwesomeness** [comment]
What? Why was this reopened?
