### ISSUE TITLE
Mob noises

### ISSUE THREAD

**Issue by PCAwesomeness** [JurassiCraft/JurassiCraft#151]
Some mobs like T.rex and Velociraptor make no sound when idle, but when hurt, they make every sound made for them.

**Comment by BobMowzie** [comment]
We know. The new sound system isn't quite done.

**Comment by Rydog101** [comment]
New sound stuff is getting there slowly

**Comment by Rydog101** [comment]
Some sounds should work still need the rest to be organised and labeled right
