### ISSUE TITLE
Server start crash for build 93-98 (java.lang.NoSuchFieldError: icons)

### ISSUE THREAD

**Issue by Maokuma** [JurassiCraft/JurassiCraft#154]
Hi, I'm sure you already know this but I'll past it here: http://pastebin.com/3DBjSWiu
Using forge 1291 with only Jurassicraft build 93 on an dedicated server.

As always, looking forward to the next updated and thanks for your great work!

**Comment by Maokuma** [comment]
Build 96 is awesome in single player and you guys have done some great stuff. Wish I could send you a beer or something.
An update on build 96 dedicated server start crash log: http://pastebin.com/eNVAxmzt

**Comment by iLexiconn** [comment]
You're using the dev build, you should use the universal build instead.

**Comment by Maokuma** [comment]
I'm sorry, I should have provided a better crash log: http://pastebin.com/QTf6N58Z
It's running on an dedicated linux server with java 1.7.0_75 (64bit). And I am using McMyAdmin with latest forge 1291 and "JurassiCraft-1.3.2-build-98-universal.jar" only.
I can replicate the error on a dedicated server software on my windows 7 computer.
On the same setup version: "JurassiCraft-1.3.2-daily_build-2015_01_15-universal" works excellent.
Thanks!

**Comment by Maokuma** [comment]
Updated the dedicated linux server with latest Java 8_31 (64bit) for a test. It was time for it anyway. But the error output is exactly the same except java version.
Am I misunderstanding that the "JurassiCraft-1.3.2-build-98-universal.jar" is actually a dev build. I'm confused.

**Comment by iLexiconn** [comment]
Sorry, It's not a dev build. I'll take a look at this bug now.

**Comment by Maokuma** [comment]
Thanks mate, this problem has been puzzling me for some time now. It should be easy to reproduce but if I can provide more data to make it easier for you dino coders, I'll be happy to.

**Comment by iLexiconn** [comment]
Could you please try build 99, reopen when still fails

**Comment by Maokuma** [comment]
It crashed again: http://pastebin.com/b7segEk3 (crash and forge log)
When you test it with a dedicated server. What software do you use to get it to work?
Thanks for the update thought, I could see you spent some time with this. I appreciate it.

**Comment by iLexiconn** [comment]
http://jenkins.ilexiconn.net/job/JurassiCraft/100/
