### ISSUE TITLE
Carnivores are no longer hostile

### ISSUE THREAD

**Issue by Kash-117** [JurassiCraft/JurassiCraft#160]
They also don't do damage or even attack back

**Comment by BobMowzie** [comment]
Are you sure? I just watched a trex take down a stegosaurus this evening.

**Comment by PCAwesomeness** [comment]
I'll see if Kash or Bob wins this.

**Comment by BobMowzie** [comment]
It took a reeeeeaally long time for the rex to notice though, and I'm not really sure which one struck first.

**Comment by PCAwesomeness** [comment]
Well, Kash is right about the carnivores not hunting stuff. However, they do fight back and they do kill you; it's just that their hitboxes are so tiny that they can only kill you if you're standing under them.

**Comment by Kash-117** [comment]
nope hitboxes are normal sized

**Comment by Kash-117** [comment]
but they don't do damage or are completely passive

**Comment by PCAwesomeness** [comment]
Are you sure? I hit a Velociraptor, and it chased after me, but it did no damage. Then, I went a step below it, and it bit me to death.

So, the hitboxes must be pretty tiny.

**Comment by Kash-117** [comment]
Nope I checked. raptors and maybe some other carnivores are passive unless provoked and 0 damage. Trex and another are hostile but 0 damage

**Comment by Kash-117** [comment]
However dinos will deal damage to other dinos if told to attack

**Comment by Kash-117** [comment]
Yeah carnivores do however attack vanilla mobs and kill them

**Comment by Kash-117** [comment]
They don't attack other dinos

**Comment by PCAwesomeness** [comment]
The Tyrannosaurus, Velociraptor, Herrerasaurus, Titanis, Orthacanthus, and Tylosaurus attack you just fine now, but the Carnotaurus is still neutral.
