### ISSUE TITLE
Trex attack range is ridiculous

### ISSUE THREAD

**Issue by BobMowzie** [JurassiCraft/JurassiCraft#165]
No idea what change is causing this, but it started sometime after I implemented the attack animation. No other carnivores have this problem.

**Comment by BobMowzie** [comment]
Neither. The attack triggers before it's close enough to its target. I have an idea for a solution.

**Comment by PCAwesomeness** [comment]
@BobMowzie 
That would count as an oversized hitbox, but OK.

Also, yay!

**Comment by BobMowzie** [comment]
It's not the hitbox. Press f3 and b to display entity hitboxes. The trex will attack before its hitbox reaches the target's.

**Comment by PCAwesomeness** [comment]
OK...
