### ISSUE TITLE
orthacanthus and coelacanth despawn 

### ISSUE THREAD

**Issue by colin5456** [JurassiCraft/JurassiCraft#166]
built a cage and put orthacanthus and coelacanth and nothing else, then i went to buld another cage and when i went back they disappeared.
Tested multiple times, and they still disappear when I move away. 
Also tested spawning, immediately saving the World and reopening: the orthacanthus were still there but when I moved away and returned they were gone again.
Looks like a bug ... only these two mobs disappear like this ...

**Comment by PCAwesomeness** [comment]
Coelacanths are supposed to despawn, and Orthacanthus are ferocious cannibals (they eat each other)... <_<

Close this, please.

**Comment by BobMowzie** [comment]
I'm thinking of making a "world gen spawned" property on each dino. This way, only coelacanths that spawn naturally will despawn and later only wild dinosaurs in the prehistoric dimension will be able to breed.
