### ISSUE TITLE
Adult dinosaurs forget how to run away from their predators

### ISSUE THREAD

**Issue by PCAwesomeness** [JurassiCraft/JurassiCraft#168]
When a baby Gallimimus/Hypsilophodon comes across a Tyrannosaurus/Herrerasaurus, it runs away, and puts up quite a chase before it gets killed. However, when an adult Gallimimus/Hypsilophodon comes across its predator, all the Tyrannosaurus/Herrerasaurus has to do is rush its prey and SNAP! The Gallimimus/Hypsilophodon is gone.

**Comment by gegy1000** [comment]
This is because the Gallimimus is a protective dinosaur. And the Hypsilophodon is a 'coward', so they should always flee.
