### ISSUE TITLE
Paraceratherium?

### ISSUE THREAD

**Issue by furrybandicoot** [JurassiCraft/JurassiCraft#175]
LOL, not sure what this thing is meant to be. I tried to get rid of all my texture packs, update my drivers for my video card, remove all other mods, and this thing still looks the same. 
Is this a w.i.p. creature or is there something wrong on my end?
![lol](https://cloud.githubusercontent.com/assets/11273970/6444541/6dce20b4-c0bb-11e4-97c5-3a9b8aba09ba.png)

**Comment by BobMowzie** [comment]
Work in progress. It was removed in the most recent build.
