### ISSUE TITLE
Dilophosaurus not using animations

### ISSUE THREAD

**Issue by Maokuma** [JurassiCraft/JurassiCraft#177]
Dilophosaurus has no animations at all but it still moves around, looking like the best day in it's life.
Happens both in Singelplayer and Multiplayer and tested with the build version 108.
I may have missed a note and this has been in the mod for a few builds. But I thought I would put it here.
//Thanks! And great work as always! Big fan!

**Comment by PCAwesomeness** [comment]
He's getting a new model soon. Same with Triceratops, Velociraptor, and Brachiosaurus.

**Comment by PCAwesomeness** [comment]
He already got a new model. Now for the animations...

**Comment by PCAwesomeness** [comment]
Dilophosaurus is now 75% animated. Please close this.
