### ISSUE TITLE
Jurassicraft 1.3.2-Final - NullPointerException - No Mob Spawn [Cauldron/Sponge]

### ISSUE THREAD

**Issue by mineme45** [JurassiCraft/JurassiCraft#183]
Hello,

Thanks for this great mod.

I have some error on my log (NullPointerException) and mob (dino) do not spawn if I don't use spawn egg.
Could you look at the logs?
http://pastebin.com/ChhbN9HA

Thanks!

**Comment by PCAwesomeness** [comment]
We are on 1.3.3 now.

Also, this bug is addressed through issue #169.

Please close this.

**Comment by mineme45** [comment]
1.3.3 is not a BETA?
I've used the last stable release.
Is think it's not the same bug as #169.
Thanks

**Comment by Rydog101** [comment]
What is the build you are using

**Comment by mineme45** [comment]
1.3.2-Final from here: http://www.mineloads.com/sD (from minecraftforum.net).
I will try the last daily build (114).
So I close this issue.
Thanks
